import Vue from "vue"
import VueRouter from "vue-router"
import routes from './routers'
import store from "@/store"

Vue.use(VueRouter);

// 解决Elementui 导航栏中vue-router 再3.0版本以上重复点击菜单报错的问题
const originalPush = VueRouter.prototype.push 
VueRouter.prototype.push = function push(location){
  return originalPush.call(this,location).catch(err=> err )
}
const navTreeData =  [
  {
    "id":0,
    "createBy": null,
    "createTime": null,
    "lastUpdateBy": null,
    "lastUpdateTime": null,
    "parentId": 0,
    "name": "基础数据",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "el-icon-s-data",
    "orderNum": 0,
    "delFlag": 0,
    "parentName": null,
    "level": 0,
    "children": [
      {
        "id": 1,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 20,
        "name": "基础设置",
        "url": null,
        "perms": null,
        "type": 1,
        "icon": "el-icon-tickets",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "基础数据",
        "level": 1,
        "children": [
          {
            "id": 2,
            "createBy": null,
            "createTime": null,
            "lastUpdateBy": null,
            "lastUpdateTime": null,
            "name": "基础策略",
            "parentId": 20,
            "url": "/BData/basicSet/BasicStrategy",
            "perms": null,
            "type": 11,
            "icon": "el-icon-tickets",
            "orderNum": 1,
            "delFlag": 0,
            "parentName": "基础数据",
            "level": 1,
           },
         {
          "id": 3,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "name": "单据类型",
          "parentId": 20,
          "url": "/BData/basicSet/BillType",
          "perms": null,
          "type": 11,
          "icon": "el-icon-tickets",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "基础数据",
          "level": 1,
         },
         {
          "id": 4,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "name": "输送线",
          "parentId": 20,
          "url": "/BData/basicSet/Conveyor",
          "perms": null,
          "type": 11,
          "icon": "el-icon-tickets",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "基础数据",
          "level": 1,
         },
         {
          "id": 5,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "name": "编码规则",
          "parentId": 20,
          "url": "/BData/basicSet/CodeRule",
          "perms": null,
          "type": 11,
          "icon": "el-icon-tickets",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "基础数据",
          "level": 1,
         },
         {
          "id": 6,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "name": "字典数据",
          "parentId": 20,
          "url": "/BData/basicSet/Enumerable",
          "perms": null,
          "type": 11,
          "icon": "el-icon-tickets",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "基础数据",
          "level": 1,
         }
        ]
      },
      {
        "id": 7,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 20,
        "name": "仓库布局",
        "url": null,
        "perms": null,
        "type": 1,
        "icon": "el-icon-tickets",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "基础数据",
        "level": 1,
        "children" : [
           {
            "id": 8,
            "createBy": null,
            "createTime": null,
            "lastUpdateBy": null,
            "lastUpdateTime": null,
            "name": "仓库管理",
            "parentId": 20,
            "url": "/BData/warehouses/Warehouse",
            "perms": null,
            "type": 1,
            "icon": "el-icon-tickets",
            "orderNum": 1,
            "delFlag": 0,
            "parentName": "基础数据",
            "level": 1,
           },
           {
            "id": 9,
            "createBy": null,
            "createTime": null,
            "lastUpdateBy": null,
            "lastUpdateTime": null,
            "name": "库区管理",
            "parentId": 20,
            "url": "/BData/warehouses/Zone",
            "perms": null,
            "type": 1,
            "icon": "el-icon-tickets",
            "orderNum": 1,
            "delFlag": 0,
            "parentName": "基础数据",
            "level": 1,
           },
           {
            "id": 10,
            "createBy": null,
            "createTime": null,
            "lastUpdateBy": null,
            "lastUpdateTime": null,
            "name": "货位管理",
            "parentId": 20,
            "url": "/BData/warehouses/Location",
            "perms": null,
            "type": 1,
            "icon": "el-icon-tickets",
            "orderNum": 1,
            "delFlag": 0,
            "parentName": "基础数据",
            "level": 1,
           },
           {
            "id": 11,
            "createBy": null,
            "createTime": null,
            "lastUpdateBy": null,
            "lastUpdateTime": null,
            "name": "货架管理",
            "parentId": 20,
            "url": "/BData/warehouses/Rack",
            "perms": null,
            "type": 1,
            "icon": "el-icon-tickets",
            "orderNum": 1,
            "delFlag": 0,
            "parentName": "基础数据",
            "level": 1,
           },
           {
            "id": 12,
            "createBy": null,
            "createTime": null,
            "lastUpdateBy": null,
            "lastUpdateTime": null,
            "name": "分区管理",
            "parentId": 20,
            "url": "/BData/warehouses/Area",
            "perms": null,
            "type": 1,
            "icon": "el-icon-tickets",
            "orderNum": 1,
            "delFlag": 0,
            "parentName": "基础数据",
            "level": 1,
           },
           {
            "id": 13,
            "createBy": null,
            "createTime": null,
            "lastUpdateBy": null,
            "lastUpdateTime": null,
            "name": "月台管理",
            "parentId": 20,
            "url": "/BData/warehouses/Dock",
            "perms": null,
            "type": 1,
            "icon": "el-icon-tickets",
            "orderNum": 1,
            "delFlag": 0,
            "parentName": "基础数据",
            "level": 1,
           },
           {
            "id": 14,
            "createBy": null,
            "createTime": null,
            "lastUpdateBy": null,
            "lastUpdateTime": null,
            "name": "巷道管理",
            "parentId": 20,
            "url": "/BData/warehouses/Laneway",
            "perms": null,
            "type": 1,
            "icon": "el-icon-tickets",
            "orderNum": 1,
            "delFlag": 0,
            "parentName": "基础数据",
            "level": 1,
           }
        ]
    },
    {
      "id": 15,
      "createBy": null,
      "createTime": null,
      "lastUpdateBy": null,
      "lastUpdateTime": null,
      "parentId": 20,
      "name": "物料管理",
      "url": null,
      "perms": null,
      "type": 1,
      "icon": "el-icon-tickets",
      "orderNum": 1,
      "delFlag": 0,
      "parentName": "基础数据",
      "level": 1,
      "children" : [
        {
          "id": 16,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "name": "物料类目",
          "parentId": 20,
          "url": "/BData/materials/MaterialCategory",
          "perms": null,
          "type": 1,
          "icon": "el-icon-tickets",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "基础数据",
          "level": 1,
         },
         {
          "id": 17,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "name": "属性规则",
          "parentId": 20,
          "url": "/BData/materials/MaterialPropertyRule",
          "perms": null,
          "type": 1,
          "icon": "el-icon-tickets",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "基础数据",
          "level": 1,
         },
         {
          "id": 18,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "name": "基础物料",
          "parentId": 20,
          "url": "/BData/materials/BasicMaterial",
          "perms": null,
          "type": 1,
          "icon": "el-icon-tickets",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "基础数据",
          "level": 1,
         },
         {
          "id": 19,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "name": "扩展属性",
          "parentId": 20,
          "url": "/BData/materials/Property",
          "perms": null,
          "type": 1,
          "icon": "el-icon-tickets",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "基础数据",
          "level": 1,
         }
      ]
  },
  {
    "id": 20,
    "createBy": null,
    "createTime": null,
    "lastUpdateBy": null,
    "lastUpdateTime": null,
    "parentId": 20,
    "name": "组织管理",
    "url": null,
    "perms": null,
    "type": 1,
    "icon": "el-icon-tickets",
    "orderNum": 1,
    "delFlag": 0,
    "parentName": "基础数据",
    "level": 1,
    "children" : [
      {
        "id": 21,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "name": "组织管理",
        "parentId": 20,
        "url": "/BData/orgnizations/Orgnization",
        "perms": null,
        "type": 1,
        "icon": "el-icon-tickets",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "基础数据",
        "level": 1,
       },
       {
        "id": 22,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "name": "部门管理",
        "parentId": 20,
        "url": "/BData/orgnizations/Department",
        "perms": null,
        "type": 1,
        "icon": "el-icon-tickets",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "基础数据",
        "level": 1,
       }
    ]
  },
  {
      "id": 23,
      "createBy": null,
      "createTime": null,
      "lastUpdateBy": null,
      "lastUpdateTime": null,
      "parentId": 0,
      "name": "载具管理",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "el-icon-tickets",
      "orderNum": 0,
      "delFlag": 0,
      "parentName": null,
      "level": 0,
      "children": [
        {
          "id": 24,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "parentId": 1,
          "name": "载具类型",
          "url": "/BData/containers/ContainerType",
          "perms": null,
          "type": 1,
          "icon": "el-icon-tickets",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "系统管理",
          "level": 1,
        },
        {
          "id": 25,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "parentId": 1,
          "name": "载具管理",
          "url": "/BData/containers/Container",
          "perms": null,
          "type": 1,
          "icon": "el-icon-tickets",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "系统管理",
          "level": 1,
        }
      ]
  },
  {
    "id": 26,
    "createBy": null,
    "createTime": null,
    "lastUpdateBy": null,
    "lastUpdateTime": null,
    "parentId": 0,
    "name": "其他",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "el-icon-tickets",
    "orderNum": 0,
    "delFlag": 0,
    "parentName": null,
    "level": 0,
    "children":[
      {
        "id": 27,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "产线管理",
        "url": "/BData/others/WorkLine",
        "perms": null,
        "type": 1,
        "icon": "el-icon-tickets",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
      },
      {
        "id": 28,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "产线备份管理",
        "url": "/BData/others/WorkLineBackup",
        "perms": null,
        "type": 1,
        "icon": "el-icon-tickets",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
      },
      {
        "id": 29,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "班组管理",
        "url": "/BData/others/WorkGroup",
        "perms": null,
        "type": 1,
        "icon": "el-icon-tickets",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
      },
      {
        "id": 30,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "车辆管理",
        "url": "/BData/others/Vehicle",
        "perms": null,
        "type": 1,
        "icon": "el-icon-tickets",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
      }
    ]
    
  }

    ]
  },
  {
    "id":31,
    "createBy": null,
    "createTime": null,
    "lastUpdateBy": null,
    "lastUpdateTime": null,
    "parentId": 0,
    "name": "入库管理",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "el-icon-setting",
    "orderNum": 0,
    "delFlag": 0,
    "parentName": null,
    "level": 0,
    "children": [
      {
        "id": 32,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "入库申请单",
        "url": "/inbound/apply/ApplyReceiptOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
        "children": []
      },
      {
        "id": 33,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "收获单管理",
        "url": "/inbound/receiptOrder/ReceiptOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
        "children": []
      },
      {
        "id": 34,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "收货记录",
        "url": "/inbound/receive/ReceiveRecord",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
        "children": []
      },
      {
        "id": 35,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "上架管理",
        "url": "/inbound/moveDoc/mvputaway",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
        "children": []
      },
    ]
  },
  {
    "id": 36,
    "createBy": null,
    "createTime": null,
    "lastUpdateBy": null,
    "lastUpdateTime": null,
    "parentId": 0,
    "name": "出库管理",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "el-icon-setting",
    "orderNum": 0,
    "delFlag": 0,
    "parentName": null,
    "level": 0,
    "children": [
      {
        "id": 37,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "出库申请单",
        "url": "/outbound/apply/ApplyShipOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
        "children": []
      },
      {
        "id": 38,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "发货单管理",
        "url": "/outbound/shipOrder/ShipOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
        "children": []
      },
      {
        "id": 39,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "拣货单管理",
        "url": "/outbound/movedoc/ShipPickOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "系统管理",
        "level": 1,
        "children": []
      },
      // {
      //   "id": 40,
      //   "createBy": null,
      //   "createTime": null,
      //   "lastUpdateBy": null,
      //   "lastUpdateTime": null,
      //   "parentId": 1,
      //   "name": "发运单管理",
      //   "url": "/outbound/ShippingOrder/ShippingOrder",
      //   "perms": null,
      //   "type": 1,
      //   "icon": "el-icon-service",
      //   "orderNum": 1,
      //   "delFlag": 0,
      //   "parentName": "系统管理",
      //   "level": 1,
      //   "children": []
      // },
      // {
      //   "id": 41,
      //   "createBy": null,
      //   "createTime": null,
      //   "lastUpdateBy": null,
      //   "lastUpdateTime": null,
      //   "parentId": 1,
      //   "name": "装车单管理",
      //   "url": "/outbound/TruckLoadingOrder/TruckLoadingOrder",
      //   "perms": null,
      //   "type": 1,
      //   "icon": "el-icon-service",
      //   "orderNum": 1,
      //   "delFlag": 0,
      //   "parentName": "系统管理",
      //   "level": 1,
      //   "children": []
      // },
       // {
      //   "id": 42,
      //   "createBy": null,
      //   "createTime": null,
      //   "lastUpdateBy": null,
      //   "lastUpdateTime": null,
      //   "parentId": 1,
      //   "name": "出库日志",
      //   "url": "/outbound/Outboundlog/Outboundlog",
      //   "perms": null,
      //   "type": 1,
      //   "icon": "el-icon-service",
      //   "orderNum": 1,
      //   "delFlag": 0,
      //   "parentName": "系统管理",
      //   "level": 1,
      //   "children": []
      // },
      // {
      //   "id": 43,
      //   "createBy": null,
      //   "createTime": null,
      //   "lastUpdateBy": null,
      //   "lastUpdateTime": null,
      //   "parentId": 1,
      //   "name": "拣选记录",
      //   "url": "/outbound/pickedRecord/pickedRecord",
      //   "perms": null,
      //   "type": 1,
      //   "icon": "el-icon-service",
      //   "orderNum": 1,
      //   "delFlag": 0,
      //   "parentName": "系统管理",
      //   "level": 1,
      //   "children": []
      // },
    ]
  },
  {
    "id": 44,
    "createBy": null,
    "createTime": null,
    "lastUpdateBy": null,
    "lastUpdateTime": null,
    "parentId": 0,
    "name": "盘点管理",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "el-icon-setting",
    "orderNum": 0,
    "delFlag": 0,
    "parentName": null,
    "level": 0,
    "children": [
      {
        "id": 45,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "盘点管理",
        "url": "/count/count/CountOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "盘点管理",
        "level": 1,
        "children": []
      },
      {
        "id": 46,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "盘点计划",
        "url": "/count/countmove/CountMove",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "盘点管理",
        "level": 1,
        "children": []
      },
      {
        "id": 47,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "盘点差异",
        "url": "/count/countrecord/Countrecord",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "盘点管理",
        "level": 1,
        "children": []
      }
    ]
  },
  {
    "id": 48,
    "createBy": null,
    "createTime": null,
    "lastUpdateBy": null,
    "lastUpdateTime": null,
    "parentId": 0,
    "name": "质检管理",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "el-icon-setting",
    "orderNum": 0,
    "delFlag": 0,
    "parentName": null,
    "level": 0,
    "children": [
      {
        "id": 49,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "质检管理",
        "url": "/inbound/apply/ApplyReceiptOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "质检管理",
        "level": 1,
        "children": []
      },
      {
        "id": 50,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "抽样管理",
        "url": "/inbound/receiptOrder/ReceiptOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "质检管理",
        "level": 1,
        "children": []
      }
    ]
  },
  {
    "id": 51,
    "createBy": null,
    "createTime": null,
    "lastUpdateBy": null,
    "lastUpdateTime": null,
    "parentId": 0,
    "name": "作业管理",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "el-icon-setting",
    "orderNum": 0,
    "delFlag": 0,
    "parentName": null,
    "level": 0,
    "children": [
      {
        "id": 52,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "任务管理",
        "url": "/workdoc/taskOrder/TaskOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "作业管理",
        "level": 1,
        "children": []
      },
      {
        "id": 53,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "历史任务",
        "url": "/workdoc/workOrder/ReceiptOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "作业管理",
        "level": 1,
        "children": []
      },
      {
        "id": 54,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "工单管理",
        "url": "/workdoc/workOrder/WorkOrder",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "作业管理",
        "level": 1,
        "children": []
      }
    ]
  },
  {
    "id": 55,
    "createBy": null,
    "createTime": null,
    "lastUpdateBy": null,
    "lastUpdateTime": null,
    "parentId": 0,
    "name": "库单管理",
    "url": null,
    "perms": null,
    "type": 0,
    "icon": "el-icon-setting",
    "orderNum": 0,
    "delFlag": 0,
    "parentName": null,
    "level": 0,
    "children": [
      {
        "id": 56,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "库存信息",
        "url": "/inventory/inventory/Inventory",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "库单管理",
        "level": 1,
        "children": []
      },
      {
        "id": 57,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "库存归档",
        "url": "/inventory/achieved/Achieved",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "库单管理",
        "level": 1,
        "children": []
      },
      {
        "id": 58,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "库存调拨",
        "url": "/inventory/mvtransfer/mvtransfer",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "库单管理",
        "level": 1,
        "children": []
      },
      {
        "id": 59,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "库存流水",
        "url": "/inventory/flow/InventoryFlow",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "库单管理",
        "level": 1,
        "children": []
      },
      {
        "id": 60,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "立库视图",
        "url": "/inventory/visualization/locationVisualization",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "库单管理",
        "level": 1,
        "children": []
      },
      {
        "id": 61,
        "createBy": null,
        "createTime": null,
        "lastUpdateBy": null,
        "lastUpdateTime": null,
        "parentId": 1,
        "name": "平库视图",
        "url": "/inventory/visualization/locViewFlat",
        "perms": null,
        "type": 1,
        "icon": "el-icon-service",
        "orderNum": 1,
        "delFlag": 0,
        "parentName": "库单管理",
        "level": 1,
        "children": []
      }
    ]
  },
  // {
  //   "id": 62,
  //   "createBy": null,
  //   "createTime": null,
  //   "lastUpdateBy": null,
  //   "lastUpdateTime": null,
  //   "parentId": 0,
  //   "name": "质检管理",
  //   "url": null,
  //   "perms": null,
  //   "type": 0,
  //   "icon": "el-icon-setting",
  //   "orderNum": 0,
  //   "delFlag": 0,
  //   "parentName": null,
  //   "level": 0,
  //   "children": [
  //     {
  //       "id": 63,
  //       "createBy": null,
  //       "createTime": null,
  //       "lastUpdateBy": null,
  //       "lastUpdateTime": null,
  //       "parentId": 1,
  //       "name": "报表定义",
  //       "url": "/inbound/apply/ApplyReceiptOrder",
  //       "perms": null,
  //       "type": 1,
  //       "icon": "el-icon-service",
  //       "orderNum": 1,
  //       "delFlag": 0,
  //       "parentName": "报表管理",
  //       "level": 1,
  //       "children": []
  //     },
  //     {
  //       "id": 64,
  //       "createBy": null,
  //       "createTime": null,
  //       "lastUpdateBy": null,
  //       "lastUpdateTime": null,
  //       "parentId": 1,
  //       "name": "报表查询",
  //       "url": "/inbound/receiptOrder/ReceiptOrder",
  //       "perms": null,
  //       "type": 1,
  //       "icon": "el-icon-service",
  //       "orderNum": 1,
  //       "delFlag": 0,
  //       "parentName": "报表管理",
  //       "level": 1,
  //       "children": []
  //     }
  //   ]
  // },
  {
      "id": 1,
      "createBy": null,
      "createTime": null,
      "lastUpdateBy": null,
      "lastUpdateTime": null,
      "parentId": 0,
      "name": "系统管理",
      "url": null,
      "perms": null,
      "type": 0,
      "icon": "el-icon-setting",
      "orderNum": 0,
      "delFlag": 0,
      "parentName": null,
      "level": 0,
      "children": [
        {
          "id": 2,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "parentId": 1,
          "name": "用户管理",
          "url": "/sys/AboutView",
          "perms": null,
          "type": 1,
          "icon": "el-icon-service",
          "orderNum": 1,
          "delFlag": 0,
          "parentName": "系统管理",
          "level": 1,
          "children": []
        },
        {
          "id": 3,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "parentId": 1,
          "name": "机构管理",
          "url": "/sys/report",
          "perms": null,
          "type": 1,
          "icon": "el-icon-news",
          "orderNum": 2,
          "delFlag": 0,
          "parentName": "系统管理",
          "level": 1,
          "children": []
        },
        {
          "id": 4,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "parentId": 1,
          "name": "角色管理",
          "url": "/sys/Loginlog",
          "perms": null,
          "type": 1,
          "icon": "el-icon-view",
          "orderNum": 4,
          "delFlag": 0,
          "parentName": "系统管理",
          "level": 1,
          "children": []
        },
        {
          "id": 5,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "parentId": 1,
          "name": "菜单管理",
          "url": "/sys/menu",
          "perms": null,
          "type": 1,
          "icon": "el-icon-menu",
          "orderNum": 5,
          "delFlag": 0,
          "parentName": "系统管理",
          "level": 1,
          "children": []
        },
        {
          "id": 6,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "parentId": 1,
          "name": "字典管理",
          "url": "/sys/dict",
          "perms": null,
          "type": 1,
          "icon": "el-icon-edit-outline",
          "orderNum": 7,
          "delFlag": 0,
          "parentName": "系统管理",
          "level": 1,
          "children": []
        },
        {
          "id": 7,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": null,
          "lastUpdateTime": null,
          "parentId": 1,
          "name": "系统配置",
          "url": "/sys/config",
          "perms": null,
          "type": 1,
          "icon": "el-icon-edit-outline",
          "orderNum": 7,
          "delFlag": 0,
          "parentName": "系统管理",
          "level": 1,
          "children": []
        },
        {
          "id": 8,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": "admin",
          "lastUpdateTime": "2018-09-23T11:32:28.000+0000",
          "parentId": 1,
          "name": "登录日志",
          "url": "/sys/loginlog",
          "perms": null,
          "type": 1,
          "icon": "el-icon-info",
          "orderNum": 8,
          "delFlag": 0,
          "parentName": "系统管理",
          "level": 1,
          "children": []
        },
        {
          "id": 9,
          "createBy": null,
          "createTime": null,
          "lastUpdateBy": "admin",
          "lastUpdateTime": "2018-09-23T11:32:28.000+0000",
          "parentId": 1,
          "name": "操作日志",
          "url": "/sys/log",
          "perms": null,
          "type": 1,
          "icon": "el-icon-info",
          "orderNum": 8,
          "delFlag": 0,
          "parentName": "系统管理",
          "level": 1,
          "children": []
        }
      ]
    },
    // {
    //   "id": 43,
    //   "createBy": "admin",
    //   "createTime": "2018-12-27T03:05:48.000+0000",
    //   "lastUpdateBy": "admin",
    //   "lastUpdateTime": "2018-12-27T03:06:39.000+0000",
    //   "parentId": 0,
    //   "name": "服务治理",
    //   "url": "",
    //   "perms": "",
    //   "type": 0,
    //   "icon": "el-icon-service",
    //   "orderNum": 2,
    //   "delFlag": 0,
    //   "parentName": null,
    //   "level": 0,
    //   "children": [
    //     {
    //       "id": 44,
    //       "createBy": "admin",
    //       "createTime": "2018-11-03T03:06:48.000+0000",
    //       "lastUpdateBy": "admin",
    //       "lastUpdateTime": "2018-12-27T03:08:11.000+0000",
    //       "parentId": 43,
    //       "name": "注册中心",
    //       "url": "http://127.0.0.1:8500",
    //       "perms": null,
    //       "type": 1,
    //       "icon": " el-icon-view",
    //       "orderNum": 0,
    //       "delFlag": 0,
    //       "parentName": "服务治理",
    //       "level": 1,
    //       "children": []
    //     }
    //   ]
    // },
    // {
    //   "id": 46,
    //   "createBy": null,
    //   "createTime": null,
    //   "lastUpdateBy": "admin",
    //   "lastUpdateTime": "2018-12-27T03:04:18.000+0000",
    //   "parentId": 0,
    //   "name": "接口文档",
    //   "url": "http://127.0.0.1:8001/swagger-ui.html",
    //   "perms": null,
    //   "type": 1,
    //   "icon": "el-icon-document",
    //   "orderNum": 3,
    //   "delFlag": 0,
    //   "parentName": null,
    //   "level": 0,
    //   "children": []
    // },
    // {
    //   "id": 38,
    //   "createBy": "admin",
    //   "createTime": "2018-12-27T02:57:29.000+0000",
    //   "lastUpdateBy": "admin",
    //   "lastUpdateTime": "2019-01-10T09:31:04.000+0000",
    //   "parentId": 0,
    //   "name": "系统监控",
    //   "url": "",
    //   "perms": "",
    //   "type": 0,
    //   "icon": "el-icon-info",
    //   "orderNum": 4,
    //   "delFlag": 0,
    //   "parentName": null,
    //   "level": 0,
    //   "children": [
    //     {
    //       "id": 39,
    //       "createBy": null,
    //       "createTime": null,
    //       "lastUpdateBy": "admin",
    //       "lastUpdateTime": "2018-12-27T03:03:45.000+0000",
    //       "parentId": 38,
    //       "name": "数据监控",
    //       "url": "http://127.0.0.1:8001/druid/login.html",
    //       "perms": null,
    //       "type": 1,
    //       "icon": "el-icon-warning",
    //       "orderNum": 0,
    //       "delFlag": 0,
    //       "parentName": "系统监控",
    //       "level": 1,
    //       "children": []
    //     },
    //     {
    //       "id": 41,
    //       "createBy": "admin",
    //       "createTime": "2018-11-02T12:02:15.000+0000",
    //       "lastUpdateBy": "admin",
    //       "lastUpdateTime": "2018-12-27T03:03:53.000+0000",
    //       "parentId": 38,
    //       "name": "服务监控",
    //       "url": "http://127.0.0.1:8000/",
    //       "perms": null,
    //       "type": 1,
    //       "icon": "el-icon-view",
    //       "orderNum": 1,
    //       "delFlag": 0,
    //       "parentName": "系统监控",
    //       "level": 1,
    //       "children": []
    //     }
    //   ]
    // },
    // {
    //   "id": 48,
    //   "createBy": "admin",
    //   "createTime": "2018-11-15T06:39:30.000+0000",
    //   "lastUpdateBy": "admin",
    //   "lastUpdateTime": "2018-11-15T06:56:18.000+0000",
    //   "parentId": 0,
    //   "name": "代码生成",
    //   "url": "/generator/generator",
    //   "perms": "",
    //   "type": 1,
    //   "icon": "el-icon-star-on",
    //   "orderNum": 5,
    //   "delFlag": 0,
    //   "parentName": null,
    //   "level": 0,
    //   "children": []
    // },
    // {
    //   "id": 60,
    //   "createBy": "admin",
    //   "createTime": "2018-11-15T06:39:30.000+0000",
    //   "lastUpdateBy": "admin",
    //   "lastUpdateTime": "2018-11-15T06:56:18.000+0000",
    //   "parentId": 0,
    //   "name": "在线用户",
    //   "url": "/sys/online",
    //   "perms": "",
    //   "type": 1,
    //   "icon": "el-icon-view",
    //   "orderNum": 5,
    //   "delFlag": 0,
    //   "parentName": null,
    //   "level": 0,
    //   "children": []
    // },
    // {
    //   "id": 61,
    //   "createBy": null,
    //   "createTime": null,
    //   "lastUpdateBy": "admin",
    //   "lastUpdateTime": "2018-11-15T06:39:43.000+0000",
    //   "parentId": 0,
    //   "name": "使用案例",
    //   "url": null,
    //   "perms": null,
    //   "type": 0,
    //   "icon": "el-icon-picture-outline",
    //   "orderNum": 6,
    //   "delFlag": 0,
    //   "parentName": null,
    //   "level": 0,
    //   "children": [
    //     {
    //       "id": 62,
    //       "createBy": null,
    //       "createTime": null,
    //       "lastUpdateBy": null,
    //       "lastUpdateTime": null,
    //       "parentId": 52,
    //       "name": "国际化",
    //       "url": "/demo/i18n",
    //       "perms": null,
    //       "type": 1,
    //       "icon": "el-icon-edit",
    //       "orderNum": 1,
    //       "delFlag": 0,
    //       "parentName": "使用案例",
    //       "level": 1,
    //       "children": []
    //     },
    //     {
    //       "id": 63,
    //       "createBy": null,
    //       "createTime": null,
    //       "lastUpdateBy": null,
    //       "lastUpdateTime": null,
    //       "parentId": 52,
    //       "name": "换皮肤",
    //       "url": "/demo/theme",
    //       "perms": null,
    //       "type": 1,
    //       "icon": "el-icon-picture",
    //       "orderNum": 2,
    //       "delFlag": 0,
    //       "parentName": "使用案例",
    //       "level": 1,
    //       "children": []
    //     }
    //   ]
    // }
  ]
 
store.commit("setNavTree", navTreeData);

const router = new VueRouter({
  // mode: "history",
  base: process.env.BASE_URL,
  routes,
});

export default router;
